/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class nl_cwi_monetdb_monetdbe_MonetNative */

#ifndef _Included_nl_cwi_monetdb_monetdbe_MonetNative
#define _Included_nl_cwi_monetdb_monetdbe_MonetNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     nl_cwi_monetdb_monetdbe_MonetNative
 * Method:    monetdbe_open
 * Signature: (Ljava/nio/ByteBuffer;[BLjava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_nl_cwi_monetdb_monetdbe_MonetNative_monetdbe_1open__Ljava_nio_ByteBuffer_2_3BLjava_nio_ByteBuffer_2
  (JNIEnv *, jclass, jobject, jbyteArray, jobject);

/*
 * Class:     nl_cwi_monetdb_monetdbe_MonetNative
 * Method:    monetdbe_open
 * Signature: (Ljava/nio/ByteBuffer;Ljava/lang/String;Ljava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_nl_cwi_monetdb_monetdbe_MonetNative_monetdbe_1open__Ljava_nio_ByteBuffer_2Ljava_lang_String_2Ljava_nio_ByteBuffer_2
  (JNIEnv *, jclass, jobject, jstring, jobject);

/*
 * Class:     nl_cwi_monetdb_monetdbe_MonetNative
 * Method:    monetdbe_close
 * Signature: (Ljava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_nl_cwi_monetdb_monetdbe_MonetNative_monetdbe_1close
  (JNIEnv *, jclass, jobject);

/*
 * Class:     nl_cwi_monetdb_monetdbe_MonetNative
 * Method:    monetdbe_error
 * Signature: (Ljava/nio/ByteBuffer;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_nl_cwi_monetdb_monetdbe_MonetNative_monetdbe_1error
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
