/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_monetdb_monetdbe_MonetNative */

#ifndef _Included_org_monetdb_monetdbe_MonetNative
#define _Included_org_monetdb_monetdbe_MonetNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_monetdb_monetdbe_MonetNative
 * Method:    monetdbe_open
 * Signature: (Ljava/lang/String;)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_org_monetdb_monetdbe_MonetNative_monetdbe_1open__Ljava_lang_String_2
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_monetdb_monetdbe_MonetNative
 * Method:    monetdbe_open
 * Signature: (Ljava/lang/String;IIII)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_org_monetdb_monetdbe_MonetNative_monetdbe_1open__Ljava_lang_String_2IIII
  (JNIEnv *, jclass, jstring, jint, jint, jint, jint);

/*
 * Class:     org_monetdb_monetdbe_MonetNative
 * Method:    monetdbe_close
 * Signature: (Ljava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_org_monetdb_monetdbe_MonetNative_monetdbe_1close
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_monetdb_monetdbe_MonetNative
 * Method:    monetdbe_query
 * Signature: (Ljava/nio/ByteBuffer;Ljava/lang/String;Lorg/monetdb/monetdbe/MonetStatement;Z)Lorg/monetdb/monetdbe/MonetResultSet;
 */
JNIEXPORT jobject JNICALL Java_org_monetdb_monetdbe_MonetNative_monetdbe_1query
  (JNIEnv *, jclass, jobject, jstring, jobject, jboolean);

/*
 * Class:     org_monetdb_monetdbe_MonetNative
 * Method:    monetdbe_result_fetch_all
 * Signature: (Ljava/nio/ByteBuffer;II)[Lorg/monetdb/monetdbe/MonetColumn;
 */
JNIEXPORT jobjectArray JNICALL Java_org_monetdb_monetdbe_MonetNative_monetdbe_1result_1fetch_1all
  (JNIEnv *, jclass, jobject, jint, jint);

/*
 * Class:     org_monetdb_monetdbe_MonetNative
 * Method:    monetdbe_result_cleanup
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_monetdb_monetdbe_MonetNative_monetdbe_1result_1cleanup
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     org_monetdb_monetdbe_MonetNative
 * Method:    monetdbe_error
 * Signature: (Ljava/nio/ByteBuffer;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_monetdb_monetdbe_MonetNative_monetdbe_1error
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_monetdb_monetdbe_MonetNative
 * Method:    monetdbe_set_autocommit
 * Signature: (Ljava/nio/ByteBuffer;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_monetdb_monetdbe_MonetNative_monetdbe_1set_1autocommit
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     org_monetdb_monetdbe_MonetNative
 * Method:    monetdbe_get_autocommit
 * Signature: (Ljava/nio/ByteBuffer;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_monetdb_monetdbe_MonetNative_monetdbe_1get_1autocommit
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_monetdb_monetdbe_MonetNative
 * Method:    monetdbe_prepare
 * Signature: (Ljava/nio/ByteBuffer;Ljava/lang/String;Lorg/monetdb/monetdbe/MonetPreparedStatement;)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_org_monetdb_monetdbe_MonetNative_monetdbe_1prepare
  (JNIEnv *, jclass, jobject, jstring, jobject);

/*
 * Class:     org_monetdb_monetdbe_MonetNative
 * Method:    monetdbe_execute
 * Signature: (Ljava/nio/ByteBuffer;Lorg/monetdb/monetdbe/MonetPreparedStatement;Z)Lorg/monetdb/monetdbe/MonetResultSet;
 */
JNIEXPORT jobject JNICALL Java_org_monetdb_monetdbe_MonetNative_monetdbe_1execute
  (JNIEnv *, jclass, jobject, jobject, jboolean);

/*
 * Class:     org_monetdb_monetdbe_MonetNative
 * Method:    monetdbe_cleanup_statement
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_monetdb_monetdbe_MonetNative_monetdbe_1cleanup_1statement
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     org_monetdb_monetdbe_MonetNative
 * Method:    monetdbe_bind
 * Signature: (Ljava/nio/ByteBuffer;Ljava/lang/Object;II)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_monetdb_monetdbe_MonetNative_monetdbe_1bind
  (JNIEnv *, jclass, jobject, jobject, jint, jint);

/*
 * Class:     org_monetdb_monetdbe_MonetNative
 * Method:    monetdbe_bind_date
 * Signature: (Ljava/nio/ByteBuffer;IIII)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_monetdb_monetdbe_MonetNative_monetdbe_1bind_1date
  (JNIEnv *, jclass, jobject, jint, jint, jint, jint);

/*
 * Class:     org_monetdb_monetdbe_MonetNative
 * Method:    monetdbe_bind_time
 * Signature: (Ljava/nio/ByteBuffer;IIIII)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_monetdb_monetdbe_MonetNative_monetdbe_1bind_1time
  (JNIEnv *, jclass, jobject, jint, jint, jint, jint, jint);

/*
 * Class:     org_monetdb_monetdbe_MonetNative
 * Method:    monetdbe_bind_timestamp
 * Signature: (Ljava/nio/ByteBuffer;IIIIIIII)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_monetdb_monetdbe_MonetNative_monetdbe_1bind_1timestamp
  (JNIEnv *, jclass, jobject, jint, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     org_monetdb_monetdbe_MonetNative
 * Method:    monetdbe_bind_null
 * Signature: (Ljava/nio/ByteBuffer;ILjava/nio/ByteBuffer;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_monetdb_monetdbe_MonetNative_monetdbe_1bind_1null
  (JNIEnv *, jclass, jobject, jint, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
