name: MonetDBe-Java Linux CI (default and Oct2020 versions from Docker, default build from source)
on:
  [push,workflow_dispatch,pull_request]

jobs:
  linux_default_slim_build:
    name: linux_default_build
    runs-on: ubuntu-latest
    container: monetdb/dev-builds:default
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Setup Maven
      uses: stCarolas/setup-maven@v4
    - name: Build with Maven
      run: scripts/build_dev.sh /usr/local
    - name: Run example class (SimpleTypes)
      run: scripts/run_dev.sh SimpleTypes
    - name: Publish Linux default slim jar
      uses: actions/upload-artifact@v2
      with:
        name: monetdbe-java-1.0-SNAPSHOT-linux-slim-default.jar
        path: /home/runner/work/MonetDBe-Java/MonetDBe-Java/java/target/monetdbe-java-1.0-SNAPSHOT-linux-slim.jar

  linux_oct_slim_build:
    name: linux_oct_build
    runs-on: ubuntu-latest
    container: monetdb/dev-builds:Oct2020
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Setup Maven
      uses: stCarolas/setup-maven@v4
    - name: Build with Maven
      run: scripts/build_dev.sh /usr/local
    - name: Run example class (SimpleTypes)
      run: scripts/run_dev.sh SimpleTypes
    - name: Publish Linux Oct2020 slim jar
      uses: actions/upload-artifact@v2
      with:
        name: monetdbe-java-1.0-SNAPSHOT-linux-slim-oct.jar
        path: /home/runner/work/MonetDBe-Java/MonetDBe-Java/java/target/monetdbe-java-1.0-SNAPSHOT-linux-slim.jar

  linux_default_dev_build:
    name: linux_default_build
    runs-on: ubuntu-latest
    container: monetdb/dev-builds:default
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Setup Maven
      uses: stCarolas/setup-maven@v4
    - name: Build with Maven
      run: scripts/build_dev.sh /usr/local
    - name: Run example class (SimpleTypes)
      run: scripts/run_dev.sh SimpleTypes

  linux_oct_dev_build:
    name: linux_oct_build
    runs-on: ubuntu-latest
    container: monetdb/dev-builds:Oct2020
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Setup Maven
      uses: stCarolas/setup-maven@v4
    - name: Build with Maven
      run: scripts/build_dev.sh /usr/local
    - name: Run example class (SimpleTypes)
      run: scripts/run_dev.sh SimpleTypes

  linux_manual_dev_build:
    name: linux_manual_build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Setup Maven
      uses: stCarolas/setup-maven@v4
    - name: Get monetdb
      run: |
        hg clone http://dev.monetdb.org/hg/MonetDB/
    - name: Compile and install MonetDB
      run: |
        cd MonetDB
        mkdir build MonetDB-default
        cd build
        pwd
        cmake ../ -DCMAKE_INSTALL_PREFIX=/home/runner/work/MonetDBe-Java/MonetDBe-Java/MonetDB/MonetDB-default/ -DPY3INTEGRATION=OFF -DWITH_CRYPTO=OFF -DCMAKE_BUILD_TYPE=Release -DASSERT=OFF -DRINTEGRATION=OFF -DINT128=ON -DSTRICT=OFF
        make install
        cd ../../
    - name: Build with Maven
      run: scripts/build_dev.sh /home/runner/work/MonetDBe-Java/MonetDBe-Java/MonetDB/MonetDB-default
    - name: Check OS arch
      run: |
        cd java
        mvn enforcer:display-info
        cd ..
    - name: Check libmonetdbe-java.so linking
      run: |
        ldd java/target/classes/lib/linux/libmonetdbe-java.so
        ls /home/runner/work/MonetDBe-Java/MonetDBe-Java/MonetDB/MonetDB-default/lib
    - name: Run example class (SimpleTypes)
      run: scripts/run_dev.sh SimpleTypes