name: MonetDBe-Java Linux CI (default and Oct2020 versions from Docker, default build from source)
on:
  [push,workflow_dispatch,pull_request]

jobs:
  linux_oct_slim_build:
    name: linux_oct_slim_build
    runs-on: ubuntu-latest
    container: monetdb/dev-builds:Oct2020
    env:
      MONETDB_INSTALL: /usr/local
      MONETDB_LIBS: /usr/local/lib
      M2_REPO_JAVA: /root/.m2/repository/monetdb/monetdbe-java/1.0-SNAPSHOT
      ARTIFACT_JAVA: monetdbe-java-1.0-SNAPSHOT-linux-slim.jar
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Setup Maven
      uses: stCarolas/setup-maven@v4
    - name: Install chrpath
      run: apt-get install -y chrpath
    - name: Install native library (libmonetdbe-java.dylib)
      run: |
        cd native
        mvn clean install -DMonetDB_dir=$MONETDB_INSTALL -P linux-release
        cd ..
    - name: Move direct dependencies (MonetDB libs)
      run: |
        mkdir collect_libs
        cp $MONETDB_LIBS/libbat.so.?? $MONETDB_LIBS/libmapi.so.?? $MONETDB_LIBS/libmonetdb5.so.?? $MONETDB_LIBS/libmonetdbe.so.? $MONETDB_LIBS/libmonetdbsql.so.?? $MONETDB_LIBS/libstream.so.?? collect_libs
    - name: Change rpath of MonetDB libraries to package
      run: |
        for file in $GITHUB_WORKSPACE/collect_libs/*; do chrpath -r '$ORIGIN/.' $file; done
    - name: Compile Java and package into jar
      run: |
        cd java
        mvn clean install -DCOLLECT_LIBS=$GITHUB_WORKSPACE/collect_libs -P linux-slim
        cd ..
    - name: Run example class (SimpleTypes)
      run: |
        javac -cp $M2_REPO_JAVA/$ARTIFACT_JAVA example/SimpleTypes.java
        java -cp $M2_REPO_JAVA/$ARTIFACT_JAVA:example/ SimpleTypes
    #TODO Change this to env variable, $var and $env.var didn't work
    - name: Publish Linux slim jar
      uses: actions/upload-artifact@v2
      with:
        name: monetdbe-java-1.0-SNAPSHOT-linux-slim.jar
        path: /root/.m2/repository/monetdb/monetdbe-java/1.0-SNAPSHOT/monetdbe-java-1.0-SNAPSHOT-linux-slim.jar

  linux_default_dev_build:
    name: linux_default_dev_build
    runs-on: ubuntu-latest
    container: monetdb/dev-builds:default
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Setup Maven
      uses: stCarolas/setup-maven@v4
    - name: Build with Maven
      run: scripts/build_dev.sh /usr/local
    - name: Run example class (SimpleTypes)
      run: scripts/run_dev.sh SimpleTypes

  linux_oct_dev_build:
    name: linux_oct_dev_build
    runs-on: ubuntu-latest
    container: monetdb/dev-builds:Oct2020
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Setup Maven
      uses: stCarolas/setup-maven@v4
    - name: Build with Maven
      run: scripts/build_dev.sh /usr/local
    - name: Run example class (SimpleTypes)
      run: scripts/run_dev.sh SimpleTypes

  #linux_manual_dev_build:
  #  name: linux_manual_dev_build
  #  runs-on: ubuntu-latest
  #  steps:
  #  - uses: actions/checkout@v2
  #  - name: Set up JDK 1.8
  #    uses: actions/setup-java@v1
  #    with:
  #      java-version: 1.8
  #  - name: Setup Maven
  #    uses: stCarolas/setup-maven@v4
  #  - name: Get monetdb
  #    run: |
  #      hg clone http://dev.monetdb.org/hg/MonetDB/
  #  - name: Compile and install MonetDB
  #    run: |
  #      cd MonetDB
  #      mkdir build MonetDB-default
  #      cd build
  #      pwd
  #      cmake ../ -DCMAKE_INSTALL_PREFIX=/home/runner/work/MonetDBe-Java/MonetDBe-Java/MonetDB/MonetDB-default/ -DPY3INTEGRATION=OFF -DWITH_CRYPTO=OFF -DCMAKE_BUILD_TYPE=Release -DASSERT=OFF -DRINTEGRATION=OFF -DINT128=ON -DSTRICT=OFF
  #      make install
  #      cd ../../
  #  - name: Build with Maven
  #    run: scripts/build_dev.sh /home/runner/work/MonetDBe-Java/MonetDBe-Java/MonetDB/MonetDB-default
  #  - name: Check libmonetdbe-java.so linking
  #    run: |
  #      ldd java/target/classes/lib/linux/libmonetdbe-java.so
  #  - name: Run example class (SimpleTypes)
  #    run: scripts/run_dev.sh SimpleTypes