name: MonetDBe-Java Linux CI (default and Oct2020 versions from Docker)
on:
  [push,workflow_dispatch,pull_request]

jobs:
  linux_default_build:
    name: linux_default_build
    runs-on: ubuntu-latest
    container: monetdb/dev-builds:default
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Setup Maven
      uses: stCarolas/setup-maven@v4
    - name: Build with Maven
      run: mvn -B package --file pom.xml -DMonetDB_dir=/usr/local
    - name: Run example class (SimpleTypes)
      run: |
        javac -cp java/target/monetdbe-java-1.0-SNAPSHOT.jar example/SimpleTypes.java
        java -classpath java/target/monetdbe-java-1.0-SNAPSHOT.jar:example SimpleTypes

  linux_oct_build:
    name: linux_oct_build
    runs-on: ubuntu-latest
    container: monetdb/dev-builds:Oct2020
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Setup Maven
      uses: stCarolas/setup-maven@v4
    - name: Build with Maven
      run: mvn -B package --file pom.xml -DMonetDB_dir=/usr/local
    - name: Run example class (SimpleTypes)
      run: |
        javac -cp java/target/monetdbe-java-1.0-SNAPSHOT.jar example/SimpleTypes.java
        java -classpath java/target/monetdbe-java-1.0-SNAPSHOT.jar:example SimpleTypes

  linux_manual_build:
    name: linux_manual_build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Setup Maven
      uses: stCarolas/setup-maven@v4
    - name: Get monetdb
      run: |
        hg clone http://dev.monetdb.org/hg/MonetDB/
    - name: Compile and install MonetDB
      run: |
        cd MonetDB
        mkdir build
        cd build
        cmake ../ -DPY3INTEGRATION=OFF -DWITH_CRYPTO=OFF -DCMAKE_BUILD_TYPE=Release -DASSERT=OFF
        cmake --build . --target ALL_BUILD --parallel 4  --config Release
        cmake --build . --target INSTALL  --config Release
        cd ../../
    - name: Build with Maven
      run: mvn -B package --file pom.xml -DMonetDB_dir=/usr/local
    - name: Run example class (SimpleTypes)
      run: |
        javac -cp java/target/monetdbe-java-1.0-SNAPSHOT.jar example/SimpleTypes.java
        java -classpath java/target/monetdbe-java-1.0-SNAPSHOT.jar:example SimpleTypes