name: MonetDBe-Java Linux dev build CI (default and Oct2020 versions from Docker, default build from source)
on:
  [push,workflow_dispatch,pull_request]

jobs:
  linux_default_dev_build:
    name: linux_default_dev_build
    runs-on: ubuntu-latest
    container: monetdb/dev-builds:default
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Setup Maven
      uses: stCarolas/setup-maven@v4
    - name: Build with Maven
      run: $GITHUB_WORKSPACE/build_dev.sh /usr/local
    - name: Run example class (SimpleTypes)
      run: $GITHUB_WORKSPACE/run_dev.sh SimpleTypes

  linux_oct_dev_build:
    name: linux_oct_dev_build
    runs-on: ubuntu-latest
    container: monetdb/dev-builds:Oct2020
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Setup Maven
      uses: stCarolas/setup-maven@v4
    - name: Build with Maven
      run: $GITHUB_WORKSPACE/build_dev.sh /usr/local
    - name: Run example class (SimpleTypes)
      run: $GITHUB_WORKSPACE/run_dev.sh SimpleTypes

  #linux_manual_dev_build:
  #  name: linux_manual_dev_build
  #  runs-on: ubuntu-latest
  #  steps:
  #  - uses: actions/checkout@v2
  #  - name: Set up JDK 1.8
  #    uses: actions/setup-java@v1
  #    with:
  #      java-version: 1.8
  #  - name: Setup Maven
  #    uses: stCarolas/setup-maven@v4
  #  - name: Get monetdb
  #    run: |
  #      hg clone http://dev.monetdb.org/hg/MonetDB/
  #  - name: Compile and install MonetDB
  #    run: |
  #      cd MonetDB
  #      mkdir build MonetDB-default
  #      cd build
  #      pwd
  #      cmake ../ -DCMAKE_INSTALL_PREFIX=/home/runner/work/MonetDBe-Java/MonetDBe-Java/MonetDB/MonetDB-default/ -DPY3INTEGRATION=OFF -DWITH_CRYPTO=OFF -DCMAKE_BUILD_TYPE=Release -DASSERT=OFF -DRINTEGRATION=OFF -DINT128=ON -DSTRICT=OFF
  #      make install
  #      cd ../../
  #  - name: Build with Maven
  #    run: $GITHUB_WORKSPACE/build_dev.sh /home/runner/work/MonetDBe-Java/MonetDBe-Java/MonetDB/MonetDB-default
  #  - name: Run example class (SimpleTypes)
  #    run: $GITHUB_WORKSPACE/run_dev.sh SimpleTypes