# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  [push]

jobs:
  build:

    runs-on: ubuntu-latest
    container: monetdb/dev-builds:default

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
      #We were getting a "mvn not found" error
    - name: Setup Maven
      uses: stCarolas/setup-maven@v4
    - name: Build with Maven
      run: mvn -B package --file pom.xml -DMonetDB_dir=/usr/local/
    - name: Check contents of jar file
      run: jar tf java/target/monetdbe-java-src-1.0-SNAPSHOT.jar
    - name: Run example class
      run: javac -cp java/target/monetdbe-java-src-1.0-SNAPSHOT.jar example/SimpleTypes.java && java -classpath java/target/monetdbe-java-src-1.0-SNAPSHOT.jar:example SimpleTypes
