name: MacOS CI - Dev build (from Homebrew)
on: [push, workflow_dispatch, pull_request]

jobs:
  mac_brew_dev_build:
    name: mac_brew_dev_build
    runs-on: macos-latest
    steps:
      #Brew build needs to run on v1.10, as new changes in default are still not released
      - uses: actions/checkout@v2
        with:
          ref: "v1.10"
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Setup Maven
        uses: stCarolas/setup-maven@v4
        with:
          maven-version: 3.6.3
      - name: Install monetdb through brew
        run: brew install monetdb
      - name: Build with Maven
        run: $GITHUB_WORKSPACE/build_dev.sh /usr/local
      - name: Run example class (SimpleTypes)
        run: $GITHUB_WORKSPACE/run_dev.sh SimpleTypes
  mac_manual_dev_build:
      name: mac_manual_dev_build
      runs-on: macos-latest
      steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Setup Maven
        uses: stCarolas/setup-maven@v4
      - name: Get brew bison
        run: brew install bison
      - name: Get monetdb
        run: git clone https://github.com/MonetDB/MonetDB
      - name: Compile and install MonetDB
        run: |
          export PATH="/usr/local/opt/bison/bin/:$PATH"
          export LDFLAGS="-L/usr/local/opt/bison/lib/"
          brew link bison --force
          echo 'export PATH="/usr/local/opt/bison/bin/:$PATH"' >> /Users/runner/.bash_profile
          source /Users/runner/.bash_profile
          cd MonetDB
          mkdir build MonetDB-default
          cd build
          cmake ../ -DCMAKE_INSTALL_PREFIX=/Users/runner/work/MonetDBe-Java/MonetDBe-Java/MonetDB/MonetDB-default/ -DPY3INTEGRATION=OFF -DCMAKE_BUILD_TYPE=Release -DASSERT=OFF -DRINTEGRATION=OFF
          make install
          cd ../../
      - name: Build with Maven
        run: $GITHUB_WORKSPACE/scripts/build_dev.sh /Users/runner/work/MonetDBe-Java/MonetDBe-Java/MonetDB/MonetDB-default/
      - name: Run example class (SimpleTypes)
        run: $GITHUB_WORKSPACE/scripts/run_dev.sh SimpleTypes
