name: MacOS CI - Dev build (from Homebrew)
on: [push, workflow_dispatch, pull_request]

jobs:
  mac_brew_dev_build:
    name: mac_brew_dev_build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: "master"
      - name: Set up JDK 2.1
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
          cache-dependency-path: '*/pom.xml'
      - name: Setup Maven
        uses: stCarolas/setup-maven@v4
      - name: Install monetdb through brew
        run: brew install monetdb
        #- name: Set up test environment
        #run: |
        #  mkdir -p $GITHUB_WORKSPACE/testdata/taxi $GITHUB_WORKSPACE/testdata/localdb
        #  wget -O testdata/taxi/yellow_tripdata_2016-01.csv https://s3.amazonaws.com/nyc-tlc/trip+data/yellow_tripdata_2016-01.csv
      - name: Build native part
        run: cd native; mvn clean install -DMonetDB_dir=/opt
      - name: Build java part
        run: cd java; mvn clean install
        #- name: Build with Maven and test
        #run: $GITHUB_WORKSPACE/build_dev.sh /usr/local false
      - name: Run example class (SimpleTypes)
        run: $GITHUB_WORKSPACE/run_dev.sh SimpleTypes
  mac_manual_dev_build:
      name: mac_manual_dev_build
      runs-on: macos-latest
      steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 2.1
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
          cache-dependency-path: '*/pom.xml'
      - name: Setup Maven
        uses: stCarolas/setup-maven@v4
      - name: Get brew bison
        run: brew install bison
      - name: Get monetdb
        run: git clone https://github.com/MonetDB/MonetDB
      - name: Compile and install MonetDB
        run: |
          export CMAKE_LIBRARY_PATH="/usr/local/opt/bison/lib"
          export PATH="/usr/local/opt/bison/bin/:$PATH"
          export LDFLAGS="-L/usr/local/opt/bison/lib/"
          cd MonetDB
          mkdir build MonetDB-default
          cd build
          cmake ../ -DCMAKE_INSTALL_PREFIX=/Users/runner/work/MonetDBe-Java/MonetDBe-Java/MonetDB/MonetDB-default/ -DPY3INTEGRATION=OFF -DCMAKE_BUILD_TYPE=Release -DASSERT=OFF -DRINTEGRATION=OFF
          make install
          cd ../../
          #- name: Set up test environment
          #run: |
          #mkdir -p $GITHUB_WORKSPACE/testdata/taxi $GITHUB_WORKSPACE/testdata/localdb
          #wget -O testdata/taxi/yellow_tripdata_2016-01.csv https://s3.amazonaws.com/nyc-tlc/trip+data/yellow_tripdata_2016-01.csv
      - name: Build native part
        run: cd native; mvn clean install -DMonetDB_dir=$GITHUB_WORKSPACE/MonetDB/MonetDB-default/
      - name: Build java part
        run: cd java; mvn clean install
          
          #- name: Build with Maven and test
          #run: $GITHUB_WORKSPACE/build_dev.sh $GITHUB_WORKSPACE/MonetDB/MonetDB-default/ false
      - name: Run example class (SimpleTypes)
        run: $GITHUB_WORKSPACE/run_dev.sh SimpleTypes
