name: MonetDBe-Java Windows CI (Oct2020 branch from source)
on:
#  [push,workflow_dispatch,pull_request]
  [workflow_dispatch]

jobs:
  windows_build:
    name: windows_build
    runs-on: windows-2019
    env:
      branch: Oct2020
    steps:
      #Java, maven, gpg and dependencies setup; set up test env
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          server-id: ossrh
          server-username: MVN_DEPLOY_USERNAME
          server-password: MVN_DEPLOY_PASSWORD
          gpg-passphrase: MVN_GPG_PASSPHRASE
      - name: Setup Maven
        uses: stCarolas/setup-maven@v4
      - name: Setup VC tools
        uses: ilammy/msvc-dev-cmd@v1
      - name: Import GPG private key for maven release
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v3
        with:
          gpg-private-key: ${{ secrets.MVN_GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.MVN_GPG_PASSPHRASE }}
      - name: Install vcpkg packages
        uses: lukka/run-vcpkg@v5
        with:
          vcpkgArguments: --triplet x64-windows libiconv openssl libxml2 pcre zlib getopt bzip2 curl
          vcpkgGitCommitId: e803bf11296d8e7900dafb41e7b1224778d33dc6
          appendedCacheKey: ${{ hashFiles(env.vcpkgResponseFile) }}
      - name: Install Bison/Flex
        run: choco install -y winflexbison
      - name: Set up test environment
        run: |
          Set-Location D:\a\MonetDBe-Java\MonetDBe-Java
          md testdata\taxi
          md testdata\localdb
          iwr -outf testdata\taxi\yellow_tripdata_2016-01.csv https://s3.amazonaws.com/nyc-tlc/trip+data/yellow_tripdata_2016-01.csv

      #Download and install MonetDB
      - name: Get monetdb
        run: |
          Set-Location c:\
          curl.exe https://dev.monetdb.org/hg/MonetDB/archive/${{ env.branch }}.zip -O
          unzip.exe ${{ env.branch }}.zip
      - name: Compile and install MonetDB
        run: |
          mkdir c:\MonetDB-${{ env.branch }}\build
          Set-Location c:\MonetDB-${{ env.branch }}\build

          cmake -G "Visual Studio 16 2019" `
            -A x64 `
            -DCMAKE_TOOLCHAIN_FILE=D:\a\MonetDBe-Java\MonetDBe-Java\vcpkg\scripts\buildsystems\vcpkg.cmake `
            -DCMAKE_INSTALL_PREFIX=C:\monetdb `
            -DTESTING=OFF `
            -DCMAKE_BUILD_TYPE=Release `
            -DASSERT=OFF `
            -DODBC=false `
            -DPY3INTEGRATION=OFF `
            -DINT128=OFF `
            ..
          cmake --build . --target ALL_BUILD --parallel 4  --config Release
          cmake --build . --target INSTALL  --config Release

      #Install native library, collect libraries, package jar, test and deploy
      #Tests are now disabled until crash and DROP TABLE bug are fixed
      #mvn clean deploy "-DMonetDB_dir=C:\monetdb" "-DVCPKG_ROOT=$Env:VCPKG_ROOT" -P release
      - name: Install native library, collect libraries, package jar, test and deploy
        run: |
          Set-Location D:\a\MonetDBe-Java\MonetDBe-Java\native
          mvn clean install "-DMonetDB_dir=C:\monetdb"
          Set-Location D:\a\MonetDBe-Java\MonetDBe-Java\java
          mvn clean deploy "-DMonetDB_dir=C:\monetdb" "-DVCPKG_ROOT=$Env:VCPKG_ROOT" -P release -DskipTests=true
        env:
          MVN_DEPLOY_USERNAME: monetdb
          MVN_DEPLOY_PASSWORD: ${{ secrets.MVN_DEPLOY_PASSWORD }}
          MVN_GPG_PRIVATE_KEY: ${{ secrets.MVN_GPG_PRIVATE_KEY }}
          MVN_GPG_PASSPHRASE: ${{ secrets.MVN_GPG_PASSPHRASE }}

      #Run example and publish jar
      - name: Run example class (SimpleTypes)
        run: |
          Set-Location D:\a\MonetDBe-Java\MonetDBe-Java\example
          javac -cp D:\a\MonetDBe-Java\MonetDBe-Java\java\target\monetdbe-java-1.0-SNAPSHOT-windows.jar SimpleTypes.java
          java -classpath ".\;D:\a\MonetDBe-Java\MonetDBe-Java\java\target\monetdbe-java-1.0-SNAPSHOT-windows.jar" SimpleTypes
      - name: Publish Windows jar
        uses: actions/upload-artifact@v2
        with:
          name: monetdbe-java-1.0-SNAPSHOT-windows.jar
          path: D:\a\MonetDBe-Java\MonetDBe-Java\java\target\monetdbe-java-1.0-SNAPSHOT-windows.jar
